input {
  http {
    port => 5044
    codec => "json"
  }
}

filter {
  split {
    field => "events"
  }
  
  mutate {
    add_field => {
      "log_message" => "%{[events][message]}"
      "log_level"   => "%{[events][level]}"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}